//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwdlyser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string LengthMinimumUserSetting {
            get {
                return ((string)(this["LengthMinimumUserSetting"]));
            }
            set {
                this["LengthMinimumUserSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HashcatFilePathSetting {
            get {
                return ((string)(this["HashcatFilePathSetting"]));
            }
            set {
                this["HashcatFilePathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public string Hashcat8664 {
            get {
                return ((string)(this["Hashcat8664"]));
            }
            set {
                this["Hashcat8664"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HashcatWorkingDirectory {
            get {
                return ((string)(this["HashcatWorkingDirectory"]));
            }
            set {
                this["HashcatWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyNameListSettings {
            get {
                return ((string)(this["CompanyNameListSettings"]));
            }
            set {
                this["CompanyNameListSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdminAccountsList {
            get {
                return ((string)(this["AdminAccountsList"]));
            }
            set {
                this["AdminAccountsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SettingTemp {
            get {
                return ((string)(this["SettingTemp"]));
            }
            set {
                this["SettingTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GetStartedAccepted {
            get {
                return ((bool)(this["GetStartedAccepted"]));
            }
            set {
                this["GetStartedAccepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideTabs {
            get {
                return ((bool)(this["HideTabs"]));
            }
            set {
                this["HideTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\AppData\\Local\\Pwdlyser\\pwdlyser-total.xml")]
        public string TotalOverTimeSettingsPath {
            get {
                return ((string)(this["TotalOverTimeSettingsPath"]));
            }
            set {
                this["TotalOverTimeSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdOverview {
            get {
                return ((string)(this["VulnIdOverview"]));
            }
            set {
                this["VulnIdOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdSource {
            get {
                return ((string)(this["VulnIdSource"]));
            }
            set {
                this["VulnIdSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdLength {
            get {
                return ((string)(this["VulnIdLength"]));
            }
            set {
                this["VulnIdLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdUsername {
            get {
                return ((string)(this["VulnIdUsername"]));
            }
            set {
                this["VulnIdUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdCompany {
            get {
                return ((string)(this["VulnIdCompany"]));
            }
            set {
                this["VulnIdCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdDict {
            get {
                return ((string)(this["VulnIdDict"]));
            }
            set {
                this["VulnIdDict"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdReuse {
            get {
                return ((string)(this["VulnIdReuse"]));
            }
            set {
                this["VulnIdReuse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdKeyboard {
            get {
                return ((string)(this["VulnIdKeyboard"]));
            }
            set {
                this["VulnIdKeyboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdDate {
            get {
                return ((string)(this["VulnIdDate"]));
            }
            set {
                this["VulnIdDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdCharFreq {
            get {
                return ((string)(this["VulnIdCharFreq"]));
            }
            set {
                this["VulnIdCharFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdHistory {
            get {
                return ((string)(this["VulnIdHistory"]));
            }
            set {
                this["VulnIdHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdWeak {
            get {
                return ((string)(this["VulnIdWeak"]));
            }
            set {
                this["VulnIdWeak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdPwned {
            get {
                return ((string)(this["VulnIdPwned"]));
            }
            set {
                this["VulnIdPwned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VulnIdAdmins {
            get {
                return ((string)(this["VulnIdAdmins"]));
            }
            set {
                this["VulnIdAdmins"] = value;
            }
        }
    }
}
