name: "dev-build-check"

on:
  push:
    branches: Dev
    paths: 
      - 'Pwdlyser.sln'
      - 'Pwdlyser/**'
      
jobs:
  dev-build:
    runs-on: [windows-latest]
    steps:

      - uses: actions/checkout@v1

      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Nuget Restore 
        run: nuget restore "Pwdlyser.sln"

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: MSBuild
        working-directory: "Pwdlyser"
        run: msbuild $Env:GITHUB_WORKSPACE\Pwdlyser\Pwdlyser.csproj /p:Configuration=Release /t:Build /p:PublicRelease=true

      - uses: actions/upload-artifact@v1
        with:
          name: Pwdlyser-dev
          path: Pwdlyser\bin\Release\Pwdlyser.exe
